[2024-02-04 01:39:17,048: INFO: main:>>>>>>>> stageData Ingestion Stagestartd <<<<<<<< ]
[2024-02-04 01:39:17,051: INFO: common:yaml_file: config/config.yaml loaded successfully]
[2024-02-04 01:39:17,052: INFO: common:yaml_file: params.yaml loaded successfully]
[2024-02-04 01:39:17,055: INFO: common:yaml_file: schema.yaml loaded successfully]
[2024-02-04 01:39:17,055: INFO: common:created directories at: artifacts]
[2024-02-04 01:39:17,056: INFO: common:created directories at: artifacts/data_ingestion]
[2024-02-04 01:39:17,756: INFO: data_ingestion:artifacts/data_ingestion/data.zip downloaded with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 5F90:190540:7B4D40:8932F4:65BE8F21
Accept-Ranges: bytes
Date: Sat, 03 Feb 2024 20:09:17 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4734-BOM
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1706990957.425443,VS0,VE324
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: c015201dfd1f3c99c2192c0e36d9f0268746382a
Expires: Sat, 03 Feb 2024 20:14:17 GMT
Source-Age: 0

]
[2024-02-04 01:39:17,758: INFO: main:>>>>>>>>stage Data Ingestion Stage completed <<<<<<<]
[2024-02-04 01:39:17,758: INFO: main:>>>>>>>> stageData Validationstartd <<<<<<<< ]
[2024-02-04 01:39:17,760: INFO: common:yaml_file: config/config.yaml loaded successfully]
[2024-02-04 01:39:17,761: INFO: common:yaml_file: params.yaml loaded successfully]
[2024-02-04 01:39:17,763: INFO: common:yaml_file: schema.yaml loaded successfully]
[2024-02-04 01:39:17,763: INFO: common:created directories at: artifacts]
[2024-02-04 01:39:17,764: INFO: common:created directories at: artifacts/data_validation]
[2024-02-04 01:39:17,764: ERROR: main:__init__() got an unexpected keyword argument 'unzip_data_dir']
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    data_validation.main()
  File "/config/workspace/End-To-End-Machine-Learning-Project/src/mlProject/pipeline/Stage_02_data_validation.py", line 14, in main
    data_validation_config = config.get_data_validation_config()
  File "/config/workspace/End-To-End-Machine-Learning-Project/src/mlProject/config/configuration.py", line 41, in get_data_validation_config
    data_validation_config = DataValidationConfig(
TypeError: __init__() got an unexpected keyword argument 'unzip_data_dir'
[2024-02-04 01:47:17,804: INFO: main:>>>>>>>> stageData Ingestion Stagestartd <<<<<<<< ]
[2024-02-04 01:47:17,807: INFO: common:yaml_file: config/config.yaml loaded successfully]
[2024-02-04 01:47:17,808: INFO: common:yaml_file: params.yaml loaded successfully]
[2024-02-04 01:47:17,810: INFO: common:yaml_file: schema.yaml loaded successfully]
[2024-02-04 01:47:17,811: INFO: common:created directories at: artifacts]
[2024-02-04 01:47:17,811: INFO: common:created directories at: artifacts/data_ingestion]
[2024-02-04 01:47:17,811: INFO: data_ingestion:file is already exist with size of23 KB]
[2024-02-04 01:47:17,813: INFO: main:>>>>>>>>stage Data Ingestion Stage completed <<<<<<<]
[2024-02-04 01:47:17,813: INFO: main:>>>>>>>> stageData Validationstartd <<<<<<<< ]
[2024-02-04 01:47:17,815: INFO: common:yaml_file: config/config.yaml loaded successfully]
[2024-02-04 01:47:17,815: INFO: common:yaml_file: params.yaml loaded successfully]
[2024-02-04 01:47:17,818: INFO: common:yaml_file: schema.yaml loaded successfully]
[2024-02-04 01:47:17,818: INFO: common:created directories at: artifacts]
[2024-02-04 01:47:17,818: INFO: common:created directories at: artifacts/data_validation]
[2024-02-04 01:47:17,818: ERROR: main:__init__() got an unexpected keyword argument 'unzip_data_dir']
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    data_validation.main()
  File "/config/workspace/End-To-End-Machine-Learning-Project/src/mlProject/pipeline/Stage_02_data_validation.py", line 14, in main
    data_validation_config = config.get_data_validation_config()
  File "/config/workspace/End-To-End-Machine-Learning-Project/src/mlProject/config/configuration.py", line 41, in get_data_validation_config
    data_validation_config = DataValidationConfig(
TypeError: __init__() got an unexpected keyword argument 'unzip_data_dir'
[2024-02-04 01:55:51,742: INFO: main:>>>>>>>> stageData Ingestion Stagestartd <<<<<<<< ]
[2024-02-04 01:55:51,745: INFO: common:yaml_file: config/config.yaml loaded successfully]
[2024-02-04 01:55:51,746: INFO: common:yaml_file: params.yaml loaded successfully]
[2024-02-04 01:55:51,748: INFO: common:yaml_file: schema.yaml loaded successfully]
[2024-02-04 01:55:51,748: INFO: common:created directories at: artifacts]
[2024-02-04 01:55:51,749: INFO: common:created directories at: artifacts/data_ingestion]
[2024-02-04 01:55:51,749: INFO: data_ingestion:file is already exist with size of23 KB]
[2024-02-04 01:55:51,750: INFO: main:>>>>>>>>stage Data Ingestion Stage completed <<<<<<<]
[2024-02-04 01:55:51,751: INFO: main:>>>>>>>> stageData Validationstartd <<<<<<<< ]
[2024-02-04 01:55:51,753: INFO: common:yaml_file: config/config.yaml loaded successfully]
[2024-02-04 01:55:51,753: INFO: common:yaml_file: params.yaml loaded successfully]
[2024-02-04 01:55:51,756: INFO: common:yaml_file: schema.yaml loaded successfully]
[2024-02-04 01:55:51,756: INFO: common:created directories at: artifacts]
[2024-02-04 01:55:51,756: INFO: common:created directories at: artifacts/data_validation]
[2024-02-04 01:55:51,756: ERROR: main:name 'DataValiadtion' is not defined]
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    data_validation.main()
  File "/config/workspace/End-To-End-Machine-Learning-Project/src/mlProject/pipeline/Stage_02_data_validation.py", line 15, in main
    data_validation = DataValiadtion(config=data_validation_config)
NameError: name 'DataValiadtion' is not defined
[2024-02-04 02:02:28,769: INFO: main:>>>>>>>> stageData Ingestion Stagestartd <<<<<<<< ]
[2024-02-04 02:02:28,772: INFO: common:yaml_file: config/config.yaml loaded successfully]
[2024-02-04 02:02:28,773: INFO: common:yaml_file: params.yaml loaded successfully]
[2024-02-04 02:02:28,775: INFO: common:yaml_file: schema.yaml loaded successfully]
[2024-02-04 02:02:28,776: INFO: common:created directories at: artifacts]
[2024-02-04 02:02:28,776: INFO: common:created directories at: artifacts/data_ingestion]
[2024-02-04 02:02:28,776: INFO: data_ingestion:file is already exist with size of23 KB]
[2024-02-04 02:02:28,778: INFO: main:>>>>>>>>stage Data Ingestion Stage completed <<<<<<<]
[2024-02-04 02:02:28,778: INFO: main:>>>>>>>> stageData Validationstartd <<<<<<<< ]
[2024-02-04 02:02:28,780: INFO: common:yaml_file: config/config.yaml loaded successfully]
[2024-02-04 02:02:28,781: INFO: common:yaml_file: params.yaml loaded successfully]
[2024-02-04 02:02:28,783: INFO: common:yaml_file: schema.yaml loaded successfully]
[2024-02-04 02:02:28,784: INFO: common:created directories at: artifacts]
[2024-02-04 02:02:28,784: INFO: common:created directories at: artifacts/data_validation]
[2024-02-04 02:02:28,797: INFO: main:>>>>>>>>stage Data Validation completed <<<<<<<]
